typography_spectrum: 0.7451847759075463
color:
  brandStrength: 0.8022244260646403
  lightness: 0.15185189596377313
  saturation: 0.8996914569288492
  rhythmicContrast: 0.42940919124521315
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.8682653594296426
name: ImagingInFlight
navigation:
  - name: Home
    url: 'http://imaginginflight.com'
    type: external
title: Ground & Aerial Imaging
description: Your World from Our Point of View
